# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bumps version and updates package in PyPI
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        key: ${{ secrets.GIT_TOKEN }}
        name: "Wyatt Sell"
        email: "profwyattb@gmail.com"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine bumpversion
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m bumpversion patch .bumpversion.cfg
        git push origin master --tags
        python setup.py sdist bdist_wheel
        twine upload dist/*
